# Generated by Django 3.0.6 on 2020-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepisowo_site', '0002_recipe_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
