# Generated by Django 3.0.6 on 2020-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="subname",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
